### PR TITLE
add money_bot

### PR DESCRIPTION
**Pull request by m4rr**
This is an example of a Ruby-based bot setup. And this code is also running as [USDRUB_bot](https://telegram.me/USDRUB_bot).

### CODE REVIEW

**Comment by DenisIzmaylov** [comment]
Hi @m4rr! Thank you very much for your contribution.

**Comment by m4rr** [comment]
Sure, let me try.

**Comment by m4rr** [comment]
Ok, got it :) @DenisIzmaylov

**Comment by DenisIzmaylov** [comment]
Thank you very MUCH! :)

**Pull request merged**
